// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Payment struct {
	PaymentID     int32
	OrderID       uuid.NullUUID
	Amount        string
	PaymentMethod string
	PaymentStatus string
	PaymentDate   sql.NullTime
}
