// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertPayments = `-- name: InsertPayments :one
INSERT INTO payments (order_id, amount, payment_method, payment_status)
VALUES ($1, $2, $3, $4)
RETURNING payment_id, order_id, amount, payment_method, payment_status, payment_date
`

type InsertPaymentsParams struct {
	OrderID       uuid.NullUUID
	Amount        float64
	PaymentMethod string
	PaymentStatus string
}

func (q *Queries) InsertPayments(ctx context.Context, arg InsertPaymentsParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, insertPayments,
		arg.OrderID,
		arg.Amount,
		arg.PaymentMethod,
		arg.PaymentStatus,
	)
	var i Payment
	err := row.Scan(
		&i.PaymentID,
		&i.OrderID,
		&i.Amount,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.PaymentDate,
	)
	return i, err
}
